---
- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  register: set_hostname
  tags: set_hostname
  when: hostname is defined

- name: Rebuild the initramfs image so hostname is reflected correctly
  command: dracut -f
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - set_hostname|changed
  tags: set_hostname

- name: Reboot to a fresh state
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  when: set_hostname | changed
  tags: set_hostname

- name: Waiting for host to be reachable
  local_action: wait_for host={{ inventory_hostname }} delay=5 port=22 state=started
  become: false
  when: set_hostname | changed
  tags: set_hostname

- name: Add host to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ ansible_nodename }}.*'
    state: absent
  when: set_hostname | changed
  tags: set_hostname

- name: Add host to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ ansible_nodename }}$'
    line: '{{ ansible_default_ipv4.address }} {{ ansible_nodename }} {{ ansible_hostname }}'
    state: present
  when: set_hostname | changed
  tags: set_hostname

- name: AWS - Ensure that hostname is preserved - remove
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: '.*preserve_hostname.*'
  state: absent
  when:
    - ansible_bios_version | search("amazon")
    - set_hostname | changed

- name: AWS - Ensure that hostname is preserved - add
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: '.*preserve_hostname.*'
    line: 'preserve_hostname: true'
  state: present
  when:
    - ansible_bios_version | search("amazon")
    - set_hostname | changed
